[build]
builder = "dockerfile"
dockerfilePath = "packages/platform/frontend/Dockerfile"
watchPatterns = ["packages/platform/frontend/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
